"""
AI Insights Service.

Generates rule-based insights from real telemetry data.
Structured for easy upgrade to LLM-powered insights later.

Architecture:
- Reads real-time data from Redis (via TelemetryCacheReader)
- Reads historical data from System B (7-day energy chart)
- All numbers are real (no mocks)
- Returns structured InsightData that maps to the frontend Insight type
"""
import logging
from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import UUID

from ...infrastructure.cache.telemetry_cache import TelemetryCacheReader
from ...infrastructure.external.system_b_client import SystemBClient, SystemBClientError

logger = logging.getLogger(__name__)

# Pakistan grid carbon intensity (kg CO2 per kWh)
CO2_KG_PER_KWH = 0.7

# Default import rate (PKR per kWh) - overridden from billing config when available
DEFAULT_PKR_RATE = 35.0

# Rotating weekly tips for the "tip of the week" section
WEEKLY_TIPS = [
    "Run dishwasher and laundry during peak solar hours (11 AM - 3 PM) to maximize savings.",
    "Pre-cool your home before 4 PM to reduce AC load during expensive evening rates.",
    "Check panel cleanliness monthly — dust reduces efficiency by up to 15% in Pakistan's dry climate.",
    "Set battery minimum reserve to 20% to extend battery lifespan significantly.",
    "Your DISCO net metering export rate earns you credit — export excess during peak solar hours.",
    "Use a timer on your water heater to heat water during midday solar surplus.",
    "Ceiling fans use 10x less power than AC — combine both on mild days to cut cooling costs.",
]


@dataclass
class InsightData:
    """A single insight generated by the service."""
    id: str
    type: str  # 'positive', 'neutral', 'warning', 'tip'
    category: str  # 'production', 'savings', 'consumption', 'anomaly', 'recommendation'
    title: str
    message: str
    timestamp: datetime
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class WeeklyDigestData:
    """Weekly energy summary digest."""
    total_generated_kwh: float
    total_saved_pkr: float
    self_sufficiency_pct: float
    prev_week_generated_kwh: float
    prev_week_saved_pkr: float
    prev_week_self_sufficiency_pct: float
    generated_change_pct: float
    saved_change_pct: float
    self_sufficiency_change_pct: float
    tip_of_the_week: str


@dataclass
class InsightsResponse:
    """Full set of insights for a site."""
    daily_insights: List[InsightData]
    anomaly_alerts: List[InsightData]
    weekly_digest: Optional[WeeklyDigestData]
    generated_at: datetime


class AIInsightsService:
    """
    Generates insights from real telemetry data.

    Data sources:
    - Real-time: Redis cache (via TelemetryCacheReader)
    - Historical: System B energy chart API (7-day / 30-day aggregates)

    The rule engine is designed so each rule can later be replaced
    with an LLM prompt call without changing the interface.
    """

    def __init__(
        self,
        telemetry_cache: TelemetryCacheReader,
        system_b_client: SystemBClient,
    ):
        self._cache = telemetry_cache
        self._system_b = system_b_client

    # =========================================================================
    # Public API
    # =========================================================================

    async def get_insights(
        self,
        site_id: UUID,
        device_serials: List[str],
        import_rate_pkr: float = DEFAULT_PKR_RATE,
    ) -> InsightsResponse:
        """
        Generate the complete set of insights for a site.

        Args:
            site_id: Site UUID (used for System B historical queries)
            device_serials: List of device serial numbers (used for Redis telemetry)
            import_rate_pkr: PKR per kWh import rate for savings calculation

        Returns:
            InsightsResponse with daily insights, anomaly alerts, and weekly digest
        """
        now = datetime.now(timezone.utc)

        # Gather aggregated site stats from Redis
        site_stats = await self._gather_site_stats(device_serials)

        # Generate daily insights
        daily_insights = self._generate_daily_insights(site_stats, import_rate_pkr, now)

        # Generate anomaly alerts
        anomaly_alerts = self._generate_anomaly_alerts(site_stats, now)

        # Generate weekly digest from System B
        weekly_digest = await self._generate_weekly_digest(site_id, import_rate_pkr)

        return InsightsResponse(
            daily_insights=daily_insights,
            anomaly_alerts=anomaly_alerts,
            weekly_digest=weekly_digest,
            generated_at=now,
        )

    # =========================================================================
    # Data Gathering
    # =========================================================================

    async def _gather_site_stats(self, device_serials: List[str]) -> Dict[str, Any]:
        """
        Aggregate real-time statistics from Redis across all site devices.

        Returns a flat dict of site-level aggregated metrics.
        """
        total_pv_w = 0.0
        total_load_w = 0.0
        total_grid_w = 0.0
        total_battery_w = 0.0
        total_energy_today_kwh = 0.0
        total_grid_import_today_kwh = 0.0
        total_grid_export_today_kwh = 0.0
        total_soc = 0.0
        soc_count = 0
        peak_power_kw = 0.0
        devices_online = 0
        devices_total = len(device_serials)

        for serial in device_serials:
            telemetry = await self._cache.get_telemetry(serial)
            status = await self._cache.get_status(serial)

            if status == "online":
                devices_online += 1

            if not telemetry:
                continue

            power = telemetry.get("power", {})
            energy = telemetry.get("energy", {})
            battery = telemetry.get("battery", {})

            pv_w = float(power.get("pv_w", 0) or 0)
            load_w = float(power.get("load_w", 0) or 0)
            grid_w = float(power.get("grid_w", 0) or 0)
            batt_w = float(power.get("battery_w", 0) or 0)
            energy_today = float(energy.get("generated_today_kwh", 0) or 0)
            grid_import = float(energy.get("grid_import_today_kwh", 0) or 0)
            grid_export = float(energy.get("grid_export_today_kwh", 0) or 0)
            soc = float(battery.get("soc_pct", 0) or 0)

            total_pv_w += pv_w
            total_load_w += load_w
            total_grid_w += grid_w
            total_battery_w += batt_w
            total_energy_today_kwh += energy_today
            total_grid_import_today_kwh += grid_import
            total_grid_export_today_kwh += grid_export

            if pv_w > 0:
                peak_power_kw = max(peak_power_kw, pv_w / 1000.0)

            if soc > 0:
                total_soc += soc
                soc_count += 1

        avg_soc = total_soc / soc_count if soc_count > 0 else 0.0

        # Self-sufficiency: solar directly consumed vs total load
        self_consumed_kwh = max(0.0, total_energy_today_kwh - total_grid_export_today_kwh)
        self_sufficiency_pct = (
            (self_consumed_kwh / total_energy_today_kwh * 100)
            if total_energy_today_kwh > 0
            else 0.0
        )

        return {
            "pv_power_w": total_pv_w,
            "load_power_w": total_load_w,
            "grid_power_w": total_grid_w,
            "battery_power_w": total_battery_w,
            "energy_today_kwh": total_energy_today_kwh,
            "grid_import_today_kwh": total_grid_import_today_kwh,
            "grid_export_today_kwh": total_grid_export_today_kwh,
            "avg_soc_pct": avg_soc,
            "peak_power_kw": peak_power_kw,
            "self_sufficiency_pct": self_sufficiency_pct,
            "self_consumed_kwh": self_consumed_kwh,
            "devices_online": devices_online,
            "devices_total": devices_total,
            "co2_saved_kg": total_energy_today_kwh * CO2_KG_PER_KWH,
        }

    # =========================================================================
    # Insight Generators
    # =========================================================================

    def _generate_daily_insights(
        self,
        stats: Dict[str, Any],
        import_rate_pkr: float,
        now: datetime,
    ) -> List[InsightData]:
        """Generate daily insights from aggregated site stats."""
        insights: List[InsightData] = []
        hour = now.hour
        energy_today = stats["energy_today_kwh"]
        peak_kw = stats["peak_power_kw"]
        self_consumed_kwh = stats["self_consumed_kwh"]
        self_sufficiency_pct = stats["self_sufficiency_pct"]
        co2_saved_kg = stats["co2_saved_kg"]

        # --- Production insight ---
        if energy_today > 0:
            insights.append(InsightData(
                id="prod-daily",
                type="positive" if energy_today >= 5 else "neutral",
                category="production",
                title="Today's Solar Generation",
                message=(
                    f"You generated {energy_today:.1f} kWh today from solar energy"
                    + (f", avoiding {co2_saved_kg:.1f} kg of CO₂" if co2_saved_kg > 0.1 else "")
                ),
                timestamp=now,
                metadata={
                    "energy_today_kwh": round(energy_today, 2),
                    "co2_saved_kg": round(co2_saved_kg, 2),
                },
            ))

        # --- Peak power insight ---
        if peak_kw > 0:
            insights.append(InsightData(
                id="peak-daily",
                type="neutral",
                category="production",
                title="Peak Solar Output",
                message=f"Peak solar output reached {peak_kw:.1f} kW today",
                timestamp=now,
                metadata={"peak_kw": round(peak_kw, 2)},
            ))

        # --- Savings insight ---
        savings_pkr = round(self_consumed_kwh * import_rate_pkr)
        if savings_pkr > 0:
            insights.append(InsightData(
                id="save-daily",
                type="positive",
                category="savings",
                title="Money Saved Today",
                message=(
                    f"You saved Rs. {savings_pkr:,} today by consuming {self_consumed_kwh:.1f} kWh "
                    f"of solar instead of grid power"
                ),
                timestamp=now,
                metadata={
                    "savings_pkr": savings_pkr,
                    "self_consumed_kwh": round(self_consumed_kwh, 2),
                    "import_rate_pkr": import_rate_pkr,
                },
            ))

        # --- Self-sufficiency insight ---
        if self_sufficiency_pct >= 80:
            insights.append(InsightData(
                id="suf-high",
                type="positive",
                category="production",
                title="High Solar Independence",
                message=(
                    f"Excellent! {self_sufficiency_pct:.0f}% of your energy today came from solar. "
                    f"You are nearly grid-independent today!"
                ),
                timestamp=now,
                metadata={"self_sufficiency_pct": round(self_sufficiency_pct, 1)},
            ))
        elif self_sufficiency_pct >= 50:
            insights.append(InsightData(
                id="suf-mid",
                type="neutral",
                category="production",
                title="Solar Coverage",
                message=(
                    f"Solar covered {self_sufficiency_pct:.0f}% of your energy needs today. "
                    f"The rest came from the grid."
                ),
                timestamp=now,
                metadata={"self_sufficiency_pct": round(self_sufficiency_pct, 1)},
            ))

        # --- Time-based optimization tip ---
        if 9 <= hour <= 15:
            insights.append(InsightData(
                id="tip-solar-hours",
                type="tip",
                category="recommendation",
                title="Peak Solar Hours Active",
                message=(
                    "Now is the best time to run high-load appliances — AC, washing machine, "
                    "dishwasher. Solar is producing maximum power right now."
                ),
                timestamp=now,
            ))
        elif 16 <= hour <= 20:
            insights.append(InsightData(
                id="tip-evening",
                type="tip",
                category="recommendation",
                title="Evening Load Tip",
                message=(
                    "Solar output is reducing now. If your battery is charged, "
                    "use battery power for evening loads to avoid grid import costs."
                ),
                timestamp=now,
            ))
        else:
            # Rotating weekly tips for non-solar hours
            tip_idx = date.today().weekday() % len(WEEKLY_TIPS)
            insights.append(InsightData(
                id="tip-weekly",
                type="tip",
                category="recommendation",
                title="Energy Saving Tip",
                message=WEEKLY_TIPS[tip_idx],
                timestamp=now,
            ))

        return insights

    def _generate_anomaly_alerts(
        self,
        stats: Dict[str, Any],
        now: datetime,
    ) -> List[InsightData]:
        """Detect anomalies from current site telemetry."""
        alerts: List[InsightData] = []
        hour = now.hour
        energy_today = stats["energy_today_kwh"]
        peak_kw = stats["peak_power_kw"]
        avg_soc = stats["avg_soc_pct"]
        devices_online = stats["devices_online"]
        devices_total = stats["devices_total"]

        # --- Low generation during daylight (panel issue or heavy cloud cover) ---
        if (
            9 <= hour <= 16
            and devices_online > 0
            and energy_today < 0.5
            and peak_kw < 0.3
        ):
            alerts.append(InsightData(
                id="anomaly-low-gen",
                type="warning",
                category="anomaly",
                title="Unusually Low Solar Generation",
                message=(
                    "Generation is much lower than expected for this time of day. "
                    "Possible causes: heavy cloud cover, panel shading, or inverter issue. "
                    "Check your system if the sky is clear."
                ),
                timestamp=now,
                metadata={"energy_today_kwh": energy_today, "peak_kw": peak_kw, "hour": hour},
            ))

        # --- Battery critically low ---
        if 0 < avg_soc < 15:
            alerts.append(InsightData(
                id="anomaly-batt-crit",
                type="warning",
                category="anomaly",
                title="Battery Critically Low",
                message=(
                    f"Battery is at {avg_soc:.0f}%. Switch non-essential loads to grid "
                    f"or reduce consumption to extend backup time."
                ),
                timestamp=now,
                metadata={"soc_pct": round(avg_soc, 1)},
            ))
        elif 0 < avg_soc < 25:
            alerts.append(InsightData(
                id="anomaly-batt-low",
                type="warning",
                category="anomaly",
                title="Battery Level Low",
                message=(
                    f"Battery at {avg_soc:.0f}%. It will recharge during the next solar window."
                ),
                timestamp=now,
                metadata={"soc_pct": round(avg_soc, 1)},
            ))

        # --- Devices offline ---
        if devices_total > 0 and devices_online == 0:
            alerts.append(InsightData(
                id="anomaly-all-offline",
                type="warning",
                category="anomaly",
                title="All Devices Offline",
                message=(
                    "No devices are reporting data. Check your internet connection "
                    "or data logger status."
                ),
                timestamp=now,
                metadata={"devices_total": devices_total},
            ))
        elif devices_total > 1 and devices_online < devices_total:
            offline_count = devices_total - devices_online
            alerts.append(InsightData(
                id="anomaly-some-offline",
                type="warning",
                category="anomaly",
                title=f"{offline_count} Device(s) Offline",
                message=(
                    f"{offline_count} of {devices_total} devices are not reporting. "
                    f"Check connectivity for offline devices."
                ),
                timestamp=now,
                metadata={"offline_count": offline_count, "devices_total": devices_total},
            ))

        return alerts

    # =========================================================================
    # Weekly Digest
    # =========================================================================

    async def _generate_weekly_digest(
        self,
        site_id: UUID,
        import_rate_pkr: float,
    ) -> Optional[WeeklyDigestData]:
        """
        Generate weekly digest from System B historical data.

        Fetches the 7-day energy chart and calculates totals.
        For now, previous-week comparison shows 0 (no two-week API yet).
        """
        try:
            current_week_data = await self._system_b.get_site_energy_chart(
                site_id=site_id,
                period="week",
            )
            data_points = current_week_data.get("data", [])

            if not data_points:
                logger.debug("No weekly data from System B for site %s", site_id)
                return None

            # Aggregate current week
            total_pv_kwh = sum(float(p.get("pv_kwh", 0) or 0) for p in data_points)
            total_load_kwh = sum(float(p.get("load_kwh", 0) or 0) for p in data_points)
            total_import_kwh = sum(float(p.get("grid_import_kwh", 0) or 0) for p in data_points)

            # Self-sufficiency calculation
            self_consumed_kwh = max(0.0, total_load_kwh - total_import_kwh)
            self_sufficiency = (
                (self_consumed_kwh / total_load_kwh * 100)
                if total_load_kwh > 0
                else (100.0 if total_pv_kwh > 0 else 0.0)
            )
            total_saved_pkr = round(self_consumed_kwh * import_rate_pkr)

            # Tip of the week
            tip = WEEKLY_TIPS[date.today().weekday() % len(WEEKLY_TIPS)]

            return WeeklyDigestData(
                total_generated_kwh=round(total_pv_kwh, 1),
                total_saved_pkr=float(total_saved_pkr),
                self_sufficiency_pct=round(self_sufficiency, 1),
                # Previous week comparison: not yet available (needs 14-day API)
                prev_week_generated_kwh=0.0,
                prev_week_saved_pkr=0.0,
                prev_week_self_sufficiency_pct=0.0,
                generated_change_pct=0.0,
                saved_change_pct=0.0,
                self_sufficiency_change_pct=0.0,
                tip_of_the_week=tip,
            )

        except (SystemBClientError, Exception) as e:
            logger.warning("Failed to generate weekly digest for site %s: %s", site_id, e)
            return None
