"""
AI Insights Service.

Generates insights from real telemetry data.
When an Anthropic API key is configured (AI_API_KEY), Claude is used to produce
richer, context-aware insights. Falls back to a rule-based engine otherwise.

Architecture:
- Reads real-time data from Redis (via TelemetryCacheReader)
- Reads historical data from System B (7-day energy chart)
- All numbers are real (no mocks)
- Returns structured InsightData that maps to the frontend Insight type
"""
import json
import logging
from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import UUID

from ...config import settings
from ...infrastructure.cache.telemetry_cache import TelemetryCacheReader
from ...infrastructure.external.system_b_client import SystemBClient, SystemBClientError

logger = logging.getLogger(__name__)

# Pakistan grid carbon intensity (kg CO2 per kWh)
CO2_KG_PER_KWH = 0.7

# Default import rate (PKR per kWh) - overridden from billing config when available
DEFAULT_PKR_RATE = 35.0

# Rotating weekly tips for the "tip of the week" section
WEEKLY_TIPS = [
    "Run dishwasher and laundry during peak solar hours (11 AM - 3 PM) to maximize savings.",
    "Pre-cool your home before 4 PM to reduce AC load during expensive evening rates.",
    "Check panel cleanliness monthly — dust reduces efficiency by up to 15% in Pakistan's dry climate.",
    "Set battery minimum reserve to 20% to extend battery lifespan significantly.",
    "Your DISCO net metering export rate earns you credit — export excess during peak solar hours.",
    "Use a timer on your water heater to heat water during midday solar surplus.",
    "Ceiling fans use 10x less power than AC — combine both on mild days to cut cooling costs.",
]

# Tool schema for Claude structured output
_CLAUDE_INSIGHT_TOOL = {
    "name": "return_insights",
    "description": (
        "Return structured daily insights and anomaly alerts for the solar site. "
        "Call this tool with every response."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "daily_insights": {
                "type": "array",
                "description": "2-4 daily insights about solar generation, savings, and recommendations.",
                "items": {
                    "type": "object",
                    "required": ["id", "type", "category", "title", "message"],
                    "properties": {
                        "id": {"type": "string"},
                        "type": {
                            "type": "string",
                            "enum": ["positive", "neutral", "warning", "tip"],
                        },
                        "category": {
                            "type": "string",
                            "enum": [
                                "production",
                                "savings",
                                "consumption",
                                "anomaly",
                                "recommendation",
                            ],
                        },
                        "title": {"type": "string", "maxLength": 60},
                        "message": {"type": "string", "maxLength": 200},
                        "metadata": {"type": "object"},
                    },
                },
            },
            "anomaly_alerts": {
                "type": "array",
                "description": "0-3 anomaly alerts. Only include real problems, not routine observations.",
                "items": {
                    "type": "object",
                    "required": ["id", "type", "category", "title", "message"],
                    "properties": {
                        "id": {"type": "string"},
                        "type": {
                            "type": "string",
                            "enum": ["positive", "neutral", "warning", "tip"],
                        },
                        "category": {
                            "type": "string",
                            "enum": [
                                "production",
                                "savings",
                                "consumption",
                                "anomaly",
                                "recommendation",
                            ],
                        },
                        "title": {"type": "string", "maxLength": 60},
                        "message": {"type": "string", "maxLength": 200},
                        "metadata": {"type": "object"},
                    },
                },
            },
        },
        "required": ["daily_insights", "anomaly_alerts"],
    },
}


@dataclass
class InsightData:
    """A single insight generated by the service."""
    id: str
    type: str  # 'positive', 'neutral', 'warning', 'tip'
    category: str  # 'production', 'savings', 'consumption', 'anomaly', 'recommendation'
    title: str
    message: str
    timestamp: datetime
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class WeeklyDigestData:
    """Weekly energy summary digest."""
    total_generated_kwh: float
    total_saved_pkr: float
    self_sufficiency_pct: float
    prev_week_generated_kwh: float
    prev_week_saved_pkr: float
    prev_week_self_sufficiency_pct: float
    generated_change_pct: float
    saved_change_pct: float
    self_sufficiency_change_pct: float
    tip_of_the_week: str


@dataclass
class InsightsResponse:
    """Full set of insights for a site."""
    daily_insights: List[InsightData]
    anomaly_alerts: List[InsightData]
    weekly_digest: Optional[WeeklyDigestData]
    generated_at: datetime


class AIInsightsService:
    """
    Generates insights from real telemetry data.

    Data sources:
    - Real-time: Redis cache (via TelemetryCacheReader)
    - Historical: System B energy chart API (7-day / 30-day aggregates)

    When AI_API_KEY is set, Claude (claude-haiku) is used to generate
    context-aware insights. Falls back to a deterministic rule engine otherwise.
    """

    def __init__(
        self,
        telemetry_cache: TelemetryCacheReader,
        system_b_client: SystemBClient,
    ):
        self._cache = telemetry_cache
        self._system_b = system_b_client
        self._claude_client = None
        self._init_claude()

    def _init_claude(self) -> None:
        """Initialise the Anthropic client if an API key is configured."""
        api_key = settings.ai.api_key
        if not api_key:
            logger.debug("AI_API_KEY not set — using rule-based insights.")
            return
        try:
            import anthropic  # type: ignore
            self._claude_client = anthropic.AsyncAnthropic(api_key=api_key)
            logger.info("Claude AI client initialised (model=%s).", settings.ai.model)
        except ImportError:
            logger.warning(
                "anthropic package not installed. "
                "Run: pip install anthropic>=0.40.0"
            )

    # =========================================================================
    # Public API
    # =========================================================================

    async def get_insights(
        self,
        site_id: UUID,
        device_serials: List[str],
        import_rate_pkr: float = DEFAULT_PKR_RATE,
    ) -> InsightsResponse:
        """
        Generate the complete set of insights for a site.

        Args:
            site_id: Site UUID (used for System B historical queries)
            device_serials: List of device serial numbers (used for Redis telemetry)
            import_rate_pkr: PKR per kWh import rate for savings calculation

        Returns:
            InsightsResponse with daily insights, anomaly alerts, and weekly digest
        """
        now = datetime.now(timezone.utc)

        # Gather aggregated site stats from Redis
        site_stats = await self._gather_site_stats(device_serials)

        # Try Claude first; fall back to rule-based on any failure
        if self._claude_client and settings.ai.enabled:
            logger.info(
                "Generating insights with Claude (model=%s) for site %s.",
                settings.ai.model,
                site_id,
            )
            try:
                daily_insights, anomaly_alerts = await self._generate_insights_with_claude(
                    site_stats, import_rate_pkr, now
                )
                logger.info(
                    "Claude insights generated successfully for site %s "
                    "(%d daily, %d anomalies).",
                    site_id,
                    len(daily_insights),
                    len(anomaly_alerts),
                )
            except Exception as exc:
                logger.warning(
                    "Claude insight generation failed for site %s (%s) — using rule-based fallback.",
                    site_id,
                    exc,
                )
                daily_insights = self._generate_daily_insights(site_stats, import_rate_pkr, now)
                anomaly_alerts = self._generate_anomaly_alerts(site_stats, now)
        else:
            logger.info(
                "Using rule-based insights for site %s "
                "(claude_client=%s, ai_enabled=%s).",
                site_id,
                bool(self._claude_client),
                settings.ai.enabled,
            )
            daily_insights = self._generate_daily_insights(site_stats, import_rate_pkr, now)
            anomaly_alerts = self._generate_anomaly_alerts(site_stats, now)

        # Weekly digest always uses System B (pure arithmetic, no LLM needed)
        weekly_digest = await self._generate_weekly_digest(site_id, import_rate_pkr)

        return InsightsResponse(
            daily_insights=daily_insights,
            anomaly_alerts=anomaly_alerts,
            weekly_digest=weekly_digest,
            generated_at=now,
        )

    # =========================================================================
    # Claude-powered insight generation
    # =========================================================================

    async def _generate_insights_with_claude(
        self,
        stats: Dict[str, Any],
        import_rate_pkr: float,
        now: datetime,
    ) -> tuple[List[InsightData], List[InsightData]]:
        """
        Ask Claude to generate insights from the aggregated site stats.

        Uses tool use to enforce a strict JSON output schema so the response
        can be deserialized without any string parsing.
        """
        hour = now.hour
        savings_pkr = round(stats["self_consumed_kwh"] * import_rate_pkr)

        system_prompt = (
            "You are an expert solar energy analyst for Pakistani residential and commercial "
            "solar installations. You generate concise, actionable insights for system owners. "
            "Write in clear English. Keep messages under 200 characters. "
            "Use Pakistani context: PKR currency, DISCO net metering, load shedding, Karachi/Lahore climate."
        )

        user_prompt = f"""Analyse the following real-time solar site data and generate insights.

## Current Site Stats
- Time: {now.strftime('%H:%M')} PKT (hour={hour})
- Solar generation today: {stats['energy_today_kwh']:.2f} kWh
- Peak solar power: {stats['peak_power_kw']:.2f} kW
- Current load: {stats['load_power_w']:.0f} W
- Current grid power: {stats['grid_power_w']:.0f} W  (positive=import, negative=export)
- Current battery power: {stats['battery_power_w']:.0f} W  (positive=charging, negative=discharging)
- Battery SoC: {stats['avg_soc_pct']:.1f}%
- Self-consumed solar today: {stats['self_consumed_kwh']:.2f} kWh
- Grid import today: {stats['grid_import_today_kwh']:.2f} kWh
- Grid export today: {stats['grid_export_today_kwh']:.2f} kWh
- Self-sufficiency today: {stats['self_sufficiency_pct']:.1f}%
- CO₂ saved today: {stats['co2_saved_kg']:.2f} kg
- Money saved today: Rs. {savings_pkr:,} (at Rs. {import_rate_pkr}/kWh)
- Devices online: {stats['devices_online']} / {stats['devices_total']}

## Instructions
- Generate 2-4 daily_insights covering: generation performance, savings, self-sufficiency, and one actionable tip for the current time of day.
- Generate anomaly_alerts ONLY if there are real problems (low generation during daylight, very low battery, devices offline). Do not generate alerts if everything is fine.
- Be specific with numbers. Avoid generic filler text.
- Call the `return_insights` tool with your response.
"""

        response = await self._claude_client.messages.create(
            model=settings.ai.model,
            max_tokens=1024,
            system=system_prompt,
            tools=[_CLAUDE_INSIGHT_TOOL],
            tool_choice={"type": "tool", "name": "return_insights"},
            messages=[{"role": "user", "content": user_prompt}],
        )

        # Extract tool_use block
        tool_use_block = next(
            (block for block in response.content if block.type == "tool_use"),
            None,
        )
        if not tool_use_block:
            raise ValueError("Claude did not call the return_insights tool.")

        raw = tool_use_block.input
        daily_insights = self._parse_insight_list(raw.get("daily_insights", []), now)
        anomaly_alerts = self._parse_insight_list(raw.get("anomaly_alerts", []), now)
        return daily_insights, anomaly_alerts

    def _parse_insight_list(
        self, items: List[Dict[str, Any]], now: datetime
    ) -> List[InsightData]:
        """Convert raw tool-use dicts into InsightData objects."""
        result: List[InsightData] = []
        for item in items:
            try:
                result.append(InsightData(
                    id=item["id"],
                    type=item["type"],
                    category=item["category"],
                    title=item["title"],
                    message=item["message"],
                    timestamp=now,
                    metadata=item.get("metadata", {}),
                ))
            except (KeyError, TypeError) as exc:
                logger.warning("Skipping malformed insight from Claude: %s — %s", item, exc)
        return result

    # =========================================================================
    # Data Gathering
    # =========================================================================

    async def _gather_site_stats(self, device_serials: List[str]) -> Dict[str, Any]:
        """
        Aggregate real-time statistics from Redis across all site devices.

        Returns a flat dict of site-level aggregated metrics.
        """
        total_pv_w = 0.0
        total_load_w = 0.0
        total_grid_w = 0.0
        total_battery_w = 0.0
        total_energy_today_kwh = 0.0
        total_grid_import_today_kwh = 0.0
        total_grid_export_today_kwh = 0.0
        total_soc = 0.0
        soc_count = 0
        peak_power_kw = 0.0
        devices_online = 0
        devices_total = len(device_serials)

        for serial in device_serials:
            telemetry = await self._cache.get_telemetry(serial)
            status = await self._cache.get_status(serial)

            if status == "online":
                devices_online += 1

            if not telemetry:
                continue

            power = telemetry.get("power", {})
            energy = telemetry.get("energy_today", {})
            battery = telemetry.get("battery", {})

            pv_w = float(power.get("pv_total_w", 0) or 0)
            load_w = float(power.get("load_w", 0) or 0)
            grid_w = float(power.get("grid_w", 0) or 0)
            batt_w = float(power.get("battery_w", 0) or 0)
            energy_today = float(energy.get("pv_kwh", 0) or 0)
            grid_import = float(energy.get("grid_import_kwh", 0) or 0)
            grid_export = float(energy.get("grid_export_kwh", 0) or 0)
            soc = float(battery.get("soc_pct", 0) or 0)

            total_pv_w += pv_w
            total_load_w += load_w
            total_grid_w += grid_w
            total_battery_w += batt_w
            total_energy_today_kwh += energy_today
            total_grid_import_today_kwh += grid_import
            total_grid_export_today_kwh += grid_export

            if pv_w > 0:
                peak_power_kw = max(peak_power_kw, pv_w / 1000.0)

            if soc > 0:
                total_soc += soc
                soc_count += 1

        avg_soc = total_soc / soc_count if soc_count > 0 else 0.0

        # Self-sufficiency: solar directly consumed vs total load
        self_consumed_kwh = max(0.0, total_energy_today_kwh - total_grid_export_today_kwh)
        self_sufficiency_pct = (
            (self_consumed_kwh / total_energy_today_kwh * 100)
            if total_energy_today_kwh > 0
            else 0.0
        )

        return {
            "pv_power_w": total_pv_w,
            "load_power_w": total_load_w,
            "grid_power_w": total_grid_w,
            "battery_power_w": total_battery_w,
            "energy_today_kwh": total_energy_today_kwh,
            "grid_import_today_kwh": total_grid_import_today_kwh,
            "grid_export_today_kwh": total_grid_export_today_kwh,
            "avg_soc_pct": avg_soc,
            "peak_power_kw": peak_power_kw,
            "self_sufficiency_pct": self_sufficiency_pct,
            "self_consumed_kwh": self_consumed_kwh,
            "devices_online": devices_online,
            "devices_total": devices_total,
            "co2_saved_kg": total_energy_today_kwh * CO2_KG_PER_KWH,
        }

    # =========================================================================
    # Rule-Based Insight Generators (fallback)
    # =========================================================================

    def _generate_daily_insights(
        self,
        stats: Dict[str, Any],
        import_rate_pkr: float,
        now: datetime,
    ) -> List[InsightData]:
        """Generate daily insights from aggregated site stats."""
        insights: List[InsightData] = []
        hour = now.hour
        energy_today = stats["energy_today_kwh"]
        peak_kw = stats["peak_power_kw"]
        self_consumed_kwh = stats["self_consumed_kwh"]
        self_sufficiency_pct = stats["self_sufficiency_pct"]
        co2_saved_kg = stats["co2_saved_kg"]

        # --- Production insight ---
        if energy_today > 0:
            insights.append(InsightData(
                id="prod-daily",
                type="positive" if energy_today >= 5 else "neutral",
                category="production",
                title="Today's Solar Generation",
                message=(
                    f"You generated {energy_today:.1f} kWh today from solar energy"
                    + (f", avoiding {co2_saved_kg:.1f} kg of CO₂" if co2_saved_kg > 0.1 else "")
                ),
                timestamp=now,
                metadata={
                    "energy_today_kwh": round(energy_today, 1),
                    "co2_saved_kg": round(co2_saved_kg, 1),
                },
            ))

        # --- Peak power insight ---
        if peak_kw > 0:
            insights.append(InsightData(
                id="peak-daily",
                type="neutral",
                category="production",
                title="Peak Solar Output",
                message=f"Peak solar output reached {peak_kw:.1f} kW today",
                timestamp=now,
                metadata={"peak_kw": round(peak_kw, 1)},
            ))

        # --- Savings insight ---
        savings_pkr = round(self_consumed_kwh * import_rate_pkr)
        if savings_pkr > 0:
            insights.append(InsightData(
                id="save-daily",
                type="positive",
                category="savings",
                title="Money Saved Today",
                message=(
                    f"You saved Rs. {savings_pkr:,} today by consuming {self_consumed_kwh:.1f} kWh "
                    f"of solar instead of grid power"
                ),
                timestamp=now,
                metadata={
                    "savings_pkr": savings_pkr,
                    "self_consumed_kwh": round(self_consumed_kwh, 1),
                    "import_rate_pkr": import_rate_pkr,
                },
            ))

        # --- Self-sufficiency insight ---
        if self_sufficiency_pct >= 80:
            insights.append(InsightData(
                id="suf-high",
                type="positive",
                category="production",
                title="High Solar Independence",
                message=(
                    f"Excellent! {self_sufficiency_pct:.0f}% of your energy today came from solar. "
                    f"You are nearly grid-independent today!"
                ),
                timestamp=now,
                metadata={"self_sufficiency_pct": round(self_sufficiency_pct, 1)},
            ))
        elif self_sufficiency_pct >= 50:
            insights.append(InsightData(
                id="suf-mid",
                type="neutral",
                category="production",
                title="Solar Coverage",
                message=(
                    f"Solar covered {self_sufficiency_pct:.0f}% of your energy needs today. "
                    f"The rest came from the grid."
                ),
                timestamp=now,
                metadata={"self_sufficiency_pct": round(self_sufficiency_pct, 1)},
            ))

        # --- Time-based optimization tip ---
        if 9 <= hour <= 15:
            insights.append(InsightData(
                id="tip-solar-hours",
                type="tip",
                category="recommendation",
                title="Peak Solar Hours Active",
                message=(
                    "Now is the best time to run high-load appliances — AC, washing machine, "
                    "dishwasher. Solar is producing maximum power right now."
                ),
                timestamp=now,
            ))
        elif 16 <= hour <= 20:
            insights.append(InsightData(
                id="tip-evening",
                type="tip",
                category="recommendation",
                title="Evening Load Tip",
                message=(
                    "Solar output is reducing now. If your battery is charged, "
                    "use battery power for evening loads to avoid grid import costs."
                ),
                timestamp=now,
            ))
        else:
            # Rotating weekly tips for non-solar hours
            tip_idx = date.today().weekday() % len(WEEKLY_TIPS)
            insights.append(InsightData(
                id="tip-weekly",
                type="tip",
                category="recommendation",
                title="Energy Saving Tip",
                message=WEEKLY_TIPS[tip_idx],
                timestamp=now,
            ))

        return insights

    def _generate_anomaly_alerts(
        self,
        stats: Dict[str, Any],
        now: datetime,
    ) -> List[InsightData]:
        """Detect anomalies from current site telemetry."""
        alerts: List[InsightData] = []
        hour = now.hour
        energy_today = stats["energy_today_kwh"]
        peak_kw = stats["peak_power_kw"]
        avg_soc = stats["avg_soc_pct"]
        devices_online = stats["devices_online"]
        devices_total = stats["devices_total"]

        # --- Low generation during daylight (panel issue or heavy cloud cover) ---
        if (
            9 <= hour <= 16
            and devices_online > 0
            and energy_today < 0.5
            and peak_kw < 0.3
        ):
            alerts.append(InsightData(
                id="anomaly-low-gen",
                type="warning",
                category="anomaly",
                title="Unusually Low Solar Generation",
                message=(
                    "Generation is much lower than expected for this time of day. "
                    "Possible causes: heavy cloud cover, panel shading, or inverter issue. "
                    "Check your system if the sky is clear."
                ),
                timestamp=now,
                metadata={"energy_today_kwh": energy_today, "peak_kw": peak_kw, "hour": hour},
            ))

        # --- Battery critically low ---
        if 0 < avg_soc < 15:
            alerts.append(InsightData(
                id="anomaly-batt-crit",
                type="warning",
                category="anomaly",
                title="Battery Critically Low",
                message=(
                    f"Battery is at {avg_soc:.0f}%. Switch non-essential loads to grid "
                    f"or reduce consumption to extend backup time."
                ),
                timestamp=now,
                metadata={"soc_pct": round(avg_soc, 1)},
            ))
        elif 0 < avg_soc < 25:
            alerts.append(InsightData(
                id="anomaly-batt-low",
                type="warning",
                category="anomaly",
                title="Battery Level Low",
                message=(
                    f"Battery at {avg_soc:.0f}%. It will recharge during the next solar window."
                ),
                timestamp=now,
                metadata={"soc_pct": round(avg_soc, 1)},
            ))

        # --- Devices offline ---
        if devices_total > 0 and devices_online == 0:
            alerts.append(InsightData(
                id="anomaly-all-offline",
                type="warning",
                category="anomaly",
                title="All Devices Offline",
                message=(
                    "No devices are reporting data. Check your internet connection "
                    "or data logger status."
                ),
                timestamp=now,
                metadata={"devices_total": devices_total},
            ))
        elif devices_total > 1 and devices_online < devices_total:
            offline_count = devices_total - devices_online
            alerts.append(InsightData(
                id="anomaly-some-offline",
                type="warning",
                category="anomaly",
                title=f"{offline_count} Device(s) Offline",
                message=(
                    f"{offline_count} of {devices_total} devices are not reporting. "
                    f"Check connectivity for offline devices."
                ),
                timestamp=now,
                metadata={"offline_count": offline_count, "devices_total": devices_total},
            ))

        return alerts

    # =========================================================================
    # Weekly Digest
    # =========================================================================

    async def _generate_weekly_digest(
        self,
        site_id: UUID,
        import_rate_pkr: float,
    ) -> Optional[WeeklyDigestData]:
        """
        Generate weekly digest from System B historical data.

        Fetches the 7-day energy chart and calculates totals.
        For now, previous-week comparison shows 0 (no two-week API yet).
        """
        try:
            current_week_data = await self._system_b.get_site_energy_chart(
                site_id=site_id,
                period="week",
            )
            data_points = current_week_data.get("data", [])

            if not data_points:
                logger.debug("No weekly data from System B for site %s", site_id)
                return None

            # Aggregate current week
            total_pv_kwh = sum(float(p.get("pv_kwh", 0) or 0) for p in data_points)
            total_load_kwh = sum(float(p.get("load_kwh", 0) or 0) for p in data_points)
            total_import_kwh = sum(float(p.get("grid_import_kwh", 0) or 0) for p in data_points)

            # Self-sufficiency calculation
            self_consumed_kwh = max(0.0, total_load_kwh - total_import_kwh)
            self_sufficiency = (
                (self_consumed_kwh / total_load_kwh * 100)
                if total_load_kwh > 0
                else (100.0 if total_pv_kwh > 0 else 0.0)
            )
            total_saved_pkr = round(self_consumed_kwh * import_rate_pkr)

            # Tip of the week
            tip = WEEKLY_TIPS[date.today().weekday() % len(WEEKLY_TIPS)]

            return WeeklyDigestData(
                total_generated_kwh=round(total_pv_kwh, 1),
                total_saved_pkr=float(total_saved_pkr),
                self_sufficiency_pct=round(self_sufficiency, 1),
                # Previous week comparison: not yet available (needs 14-day API)
                prev_week_generated_kwh=0.0,
                prev_week_saved_pkr=0.0,
                prev_week_self_sufficiency_pct=0.0,
                generated_change_pct=0.0,
                saved_change_pct=0.0,
                self_sufficiency_change_pct=0.0,
                tip_of_the_week=tip,
            )

        except (SystemBClientError, Exception) as e:
            logger.warning("Failed to generate weekly digest for site %s: %s", site_id, e)
            return None
